"""
This is a setup.py script generated by py2applet and modified for vpl3

Usage:
    python setup.py py2app
"""

from setuptools import setup

APPNAME = "Serve File"
APP = ['serve_via_http.py']
OPTIONS = {
    "argv_emulation": True,
    "dist_dir": ".",
    "plist": {
        "CFBundleIdentifier": "ch.epfl.mobots.http-file-server",
        "CFBundleVersion": "0.1",
        "NSHumanReadableCopyright":
            "2019, École polytechnique fédérale de Lausanne (EPFL). Author: Yves Piguet.",
        "CFBundleDocumentTypes": [
            {
                "CFBundleTypeExtensions": ["html", "htm"],
                "CFBundleTypeName": "HTML document",
                "CFBundleTypeRole": "Viewer"
            },
            {
                "CFBundleTypeExtensions": ["jpg"],
                "CFBundleTypeRole": "Viewer"
            },
        ],
    }
}

setup(
    name=APPNAME,
    app=APP,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
